version: '3'
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    expose: 
      - 9000
    environment:
      VIRTUAL_HOST: $PORTAINER_VHOST
      VIRTUAL_PORT: 9000 
    network_mode: bridge
    tty: true
    stdin_open: true
volumes:
  portainer_data:
